import React, { useState } from "react"
import Article from "../../components/Article/Aritcle"
import Header from "../../components/Header/Header"

const Galery =() =>{    

    const people = [
        {
          name: 'Calvin Hawkins',
          email: 'calvin.hawkins@example.com',
          image:
            'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol.JPG?raw=true',
        },
        {
          name: 'Kristen Ramos',
          email: 'kristen.ramos@example.com',
          image:
            'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_1.JPG?raw=true',
        },
        {
          name: 'Ted Fox',
          email: 'ted.fox@example.com',
          image:
            'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_125.JPG?raw=true',
        },
        {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_126.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_127.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_134.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_139.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_2.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_92.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria/Mademarmol_98.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/17c0f151-8a07-466c-a8f5-c536b0ae59e7.JPG?raw=true',
          },

          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/225450c6-d3e3-4e58-be87-c7b212536eea.JPG?raw=true',
          },

          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/2a8e6d68-75d0-49ed-8b59-6235ec509054.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/424975e7-ef4b-432c-bb0e-27c5798ac706.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/59e12ad3-9d0b-4ae9-a545-ccc7bc2dfec3.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/fb6191ac-f2b7-479c-b171-4c0b34b3fe03.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/fa72fd9f-c54b-42b3-8fdd-1ca37462c4a3.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/ed4aaf1a-a257-41e5-bf24-29869ba805ca.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/eac3fc49-057f-4a91-94d7-d5e1b0d046ed.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/d04d8c3c-a53f-4037-96b1-8359dede8787.JPG?raw=true',
          },
          {
            name: 'Ted Fox',
            email: 'ted.fox@example.com',
            image:
              'https://github.com/rolandoto/galeria/blob/main/galeria-faltante/c1a85900-faac-41d5-88e2-0ec20a73ca9e.JPG?raw=true',
          },
      ]

      const [images,setImages] =useState(people)

      const sinterizadas = [
        {
          id: "01",
          title: "Quartz",
          price: 24.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30.jpg?raw=true",
          image02: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque. ",
        },
        {
          id: "02",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-24%202.jpg?raw=true",
          image02: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-24%202.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-24%202.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "03",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-25%203.jpg?raw=true",
          image02: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-25%203.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-25%203.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "04",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-25.jpg?raw=true",
          image02: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-25.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-00-25.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "05",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2017.jpg?raw=true",
          image02: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2017.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2017.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "06",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2018.jpg?raw=true",
          image02: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2018.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2018.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "07",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2019.jpg?raw=true",
          image02:"https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2019.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2019.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "08",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2020.jpg?raw=true",
          image02:"https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2020.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-06-41%2020.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "09",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%202.jpg?raw=true",
          image02:"https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%202.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%202.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "10",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%203.jpg?raw=true",
          image02:"https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%203.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%203.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "11",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%204.jpg?raw=true",
          image02:"https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%204.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30%204.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
        {
          id: "12",
          title: "Quartz",
          price: 115.0,
          image: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30.jpg?raw=true",
          image02:"https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30.jpg?raw=true",
          image03: "https://github.com/rolandoto/galeria/blob/main/incuba/PHOTO-2022-09-10-11-07-30.jpg?raw=true",
          category: "Sinterizados",
          disp:"2",
          desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta ad et est, fugiat repudiandae neque illo delectus commodi magnam explicabo autem voluptates eaque velit vero facere mollitia. Placeat rem, molestiae error obcaecati enim doloribus impedit aliquam, maiores qui minus neque.",
        },
      ]

    const quartz =[
      {
        id: "13",
        title: "BEIGE CHISPAS CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Combinación de elementos con mas del 93 % de cuarzo , resinas ,tintes y otros secretos de la industria. Sencillez y sobriedad para tus espacios, inspírate, diseña y crea tus espacios deseados",
      },
      {
        id: "14",
        title: "BEIGE POLAR CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: " Laminas de cuarzo Hipo alergénicas de alta calidad. Quartzstone con gran fuerza estética, que hace posible decoraciones en perfecto equilibrio junto a tonos neutros o complementarios y que destaca sobremanera en escenarios de líneas más puras en color y mobiliario.",
      },
      {
        id: "15",
        title: "BLANCO CHISPAS CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "BLANCO CHISPAS CHAPA Un  lenguaje cromático único por la pureza de su blanco, nunca antes  visto en su gama tonal. Impoluta y resplandeciente, permite componer superficies de una bella pulcritud visual, en conexión con idílicos paisajes nevados. Con su presencia, esta gran familia de QUARTZSTONE alcanza una nueva dimensión estética para el campo de las aplicaciones, sin perder de vista los beneficios propios de estas piedras milenarias: dureza extrema, elevada resistencia y fácil mantenimiento.",
      },
      {
        id: "16",
        title: "BLANCO POLAR CUARZO",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Laminas de cuarzo Grupo Quartz Amplia variedad en colores y superficies. Su elegancia atemporal, su dureza sobresaliente y su resistencia a la abrasión lo convierten en un material perfecto para exteriores e interiores. Con él la autenticidad y la funcionalidad son sinónimo de una belleza innovadora.",
      },
      {
        id: "17",
        title: "CAFÉ CHISPAS CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Laminas de cuarzo Grupo Quartz , respaldo, calidad y experiencia. Estos  son cautivadores y desafiantes. El QUARTZSTONE CAFÉ CHISPAS de gran intensidad visual es sinónimo de una elegancia terrenal sublime.",
      },
      {
        id: "18",
        title: "GRIS CLARO CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Laminas de cuarzo de  1.80 x 3.20  Grupo Quartz. Con una belleza muy radical. Así llega el QUARTZSTONE Gris oscuro a las decoraciones domésticas que apuestan por las soluciones audaces y a la última tendencia.",
      },
      {
        id: "19",
        title: "GRIS POLAR CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "laminas de cuarzo de superior calidad. La magnífica personalidad del QUARTZSTONE y sus imbatibles propiedades técnicas, las convierten en las piedras naturales más cotizadas y codiciadas del momento. La mejor opción para superficies de cocinas, mesas, paredes interiores o lavados. Las diferentes variedades QUARTZSTONE ofrecen una amplia gama de tonos y patrones que agregan su belleza a los beneficios de este material famoso por su  dureza y personalidad.Catalogo - Emporeo stone",
      },
  
      {
        id: "20",
        title: "NEGRO CHISPAS CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Su impenetrable negro, imagen misma de la sobriedad y la elegancia extrema, NEGRO CHISPAS  enamora por su contundente presencia y su versatilidad estética. El negro va bien con todo, y en especial el de este producto que ofrece un color sin fisuras, totalmente puro. En ambientes claros, con blancos y crudos, el contraste de NEGRO CHISPAS será exquisito: un binomio cromático tradicional con garantía de éxito seguro; pero si además se integra en una decoración high tech, con superficies vestidas de acero, cristal y muebles de líneas rectas, el resultado estético será la quintaesencia de una fría sofisticación. Este producto no desmerece tampoco en atmósferas más cálidas, con colores y texturas suaves que contrarrestan su fuerza.",
      },
    ]

    const granitos =[
      {
        id: "21",
        title: "Sandalus",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Granito de Brasil en el que se mezclan tonalidades tierra que generan en este material un gran impacto a la vista gracias a su excentricidad y elegancia. Se puede instalar en fachadas, mesones para cocina, piso o como elemento decorativo en libro abierto.",
      },
      {
        id: "22",
        title: "Alpinus",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-alpinus.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-alpinus.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-alpinus.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Tiene un fondo crema, con vetas verdosas, cafés, negras y grisáceas; tiene además en su superficie algunos brillos muy marcados que lo hacen sofisticado y muy singular.",
      },
  
      {
        id: "23",
        title: "Black Mosaic",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-black-mosaic.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-black-mosaic.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-black-mosaic.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Es uno de los materiales más exclusivos y novedosos, debido a la cantidad de piedras petrificadas que hay en él; visualmente impacta. Idóneo para evocar naturaleza al máximo. Su compactación en las montañas nos regala exclusividad absoluta en esta piedra.",
      },
      {
        id: "24",
        title: "Blanco Macaubas",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-macaubas.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-macaubas.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-macaubas.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Sus vetas delgadas de color negro sobresalen en el fondo claro cremoso que encontramos en esta piedra; genera visualmente movimiento y tranquilidad.",
      },
      {
        id: "25",
        title: "Crystal Fjord",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-crystal-fjord-2.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-crystal-fjord-2.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-crystal-fjord-2.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Con componentes de cristal, es un exótico muy valorado. Cuenta con vetas poco comunes, simples y delicadas en tonalidades rosa claro, dorado y blanco.",
      },
      {
        id: "26",
        title: "Gaya",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-gaya.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-gaya.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-gaya.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "De verdes claros a verdes matizados van sus fondos combinados con vetas grises y cafés. Es uno de los colores más desafiantes de las canteras y de las gamas más altas de las mismas; ofrece a los diseñadores y arquitectos una amplia lista de posibilidades para introducir belleza natural a los más",
      },
      {
        id: "27",
        title: "Copacabana",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-copacabana.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-copacabana.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-copacabana.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Sus vetas fuertes en color blanco, café, crema y dorado hacen resaltar su fondo negro elegante y brillante con infinitas posibilidades de aplicación en interiores y exteriores.",
      },
      {
        id: "28",
        title: "Tornado",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Esta cuarcita tiene gran acogida gracias a sus tonalidades claras parecidas al Calacatta que inspiran sobriedad y elegancia. Sus vetas grises lo hace un material excepcionalmente único y apto para cualquier tipo de espacio y proyecto.",
      },
      {
        id: "29",
        title: "Galápagos",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/05/ganito-exotico-galapagos.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/05/ganito-exotico-galapagos.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/05/ganito-exotico-galapagos.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Con sus vetas grises, cafés y cremas se vuelve uno de los materiales más versátiles en cuanto a decoración y diseño. La simpleza y limpieza de sus líneas rememora un movimiento horizontal perfecto para llevar a las tendencias de interiorismo y diseño actuales. Puede crear libro abierto para componer espacios diferenciadores y sofisticados.",
      },
      {
        id: "30",
        title: "Giotto",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-giotto.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-giotto.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-giotto.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Casi como si hubieran escrito en su superficie con un pincel, así se siente este granito natural. Resaltan sus delgadas vetas negras y grises oscuras; simples, artísticas y elegantes. Una piedra con colores tendencia.",
      },
      {
        id: "31",
        title: "Maori",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maori.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maori.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maori.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Color básico para proyectos excepcionales. Su fondo negro muy brillante refleja la veta horizontal blanca que le compone. Es un granito clásico y diferenciador.",
      },
      {
        id: "32",
        title: "Maskaratus",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maskaratus.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maskaratus.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maskaratus.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "El Maskaratus es procedente de Brasil, impacta con sus tonos y vetas marcadas que hacen distinción entre los demás granitos exóticos. Su color principal es el verde en una mezcla arriesgada entre cremas y marrones. Es una piedra natural que presenta gran variedad en su composición lo cual hace que sea imponente y única",
      },
      {
        id: "33",
        title: "Metallic",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-metallic.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-metallic.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-metallic.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "El Metallic es un granito procedente de Brasil, su particular acabado realza la belleza de sus vetas mezcladas entre negro, matices de grises y ocres en un negro profundo que lo convierte en el protagonista de cualquier espacio donde sea instalado, ya sea para mesones de cocina, enchapes, pisos y demás.",
      },
      {
        id: "34",
        title: "Meteorus",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-meteorus.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-meteorus.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-meteorus.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Meteorus es una piedra brasilera, cuya apariencia y colores neutros genera sensación de sobriedad, sobre un fondo negro mate que combinan con vetas circulares de color purpura brillante que resaltan la belleza del material.",
      },
      {
        id: "35",
        title: "Nacarado",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-nacarado.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-nacarado.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-nacarado.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Nacarado es una piedra brasilera, con vetas en gama de dorados y bellos matices en color ámbar que aportan gran luminosidad y amplitud, dando un toque de elegancia y exclusividad al espacio. Es un material con el cual se le puede dar continuidad a la veta, haciendo una instalación en libro abierto, creando así imágenes majestuosas.",
      },
      {
        id: "36",
        title: "Rocky Mountain",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-mountain.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-mountain.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-mountain.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "El Granito Rocky Mountain (Dakota) es de origen brasilero, tiene una mezcla de vetas en colores crema, grises, negro y purpura, muy dinámicas, que le dan una apariencia muy sofisticada y elegante. Ideal para mesones, barras, escaleras, enchapes y demás.",
      },
      {
        id: "37",
        title: "Roma Imperiale",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Roma Imperiale es un granito de Brasil único y acogedor. Ofrece un fondo claro atravesado por vetas brillantes de oro, ocre y marrón. Su aspecto único es ideal para los logros originales e innovadoras de proyectos tanto para ambientes interiores y exteriores. Muy interesante es la combinación con la madera.",
      },
      {
        id: "38",
        title: "Sandalus",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-sandalus.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-sandalus.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-sandalus.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Granito de Brasil en el que se mezclan tonalidades tierra que generan en este material un gran impacto a la vista gracias a su excentricidad y elegancia. Se puede instalar en fachadas, mesones para cocina, piso o como elemento decorativo en libro abierto.",
      },
      {
        id: "39",
        title: "Santorini",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-santorini.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-santorini.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-santorini.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "El granito Santorini es de Brasil. Su alto componente de mineral de hierro le brinda una alta dureza. De color gris y vetas amarillas, naranjas y cremas. Ideal para ser el protagonista en cualquier espacio.",
      },
      {
        id: "40",
        title: "Splendor Gold",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-splendor-gold.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-splendor-gold.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-splendor-gold.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "El splendor gold es de origen brasilero, en este material se plasma una mezcla entre dorado, beige, negro y marrón con reflejos tornasol que logra un balance armonioso y hacen de este granito un material fácil de combinar y de generar contrastes.",
      },
      {
        id: "41",
        title: "Tornado",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Esta cuarcita tiene gran acogida gracias a sus tonalidades claras parecidas al Calacatta que inspiran sobriedad y elegancia. Sus vetas grises lo hace un material excepcionalmente único y apto para cualquier tipo de espacio y proyecto.",
      },
      {
        id: "42",
        title: "Yellow Cuarcita",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-yellow-cuarcita.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-yellow-cuarcita.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-yellow-cuarcita.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Esta cuarcita es ideal para exteriores, gracias a su alta resistencia a los cambios de temperatura. Son muy duras y de escasa porosidad. Sus vetas mezcladas en tonos marrones, ocres y cremas hacen de este un material fácil de combinar en cualquier ambiente. En la naturaleza se encuentra prácticamente en cualquier color dependiendo de los elementos químicos que haya en la roca, siendo los más habituales los grises, amarillos, blancos y rojos. A partir de ellas se puede crear una gran cantidad de proyectos, revestimientos de superficies y otros elementos, siendo muy habituales los mesones de cocinas y las placas decorativas destinadas al exterior de las viviendas",
      },
      {
        id: "43",
        title: "Venom Light",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-venom.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-venom.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-venom.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Esta cuarcita es impactante a la vista, sus colores claros y sus vetas irregulares le dan excentricidad a cualquier proyecto. Esta cuarcita es ideal para exteriores, gracias a su alta resistencia a los cambios de temperatura. Son muy duras y de escasa porosidad.",
      },
      {
        id: "44",
        title: "Xango Red",
        price: 115.0,
        image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-xango-red.jpg",
        image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-xango-red.jpg",
        image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-xango-red.jpg",
        category: "Granitos exoticos",
        disp:"2",
        desc: "Xango red Granito natural de origen brasilero. Tiene como particularidad que su fondo es de un llamativo tono rojo intenso en combinación con sus vetas oscuras. Es un excelente material para realizar proyectos muy específicos y exclusivos.",
      },
    ]

    const quartone =[

      {
        id: "13",
        title: "BEIGE CHISPAS CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Combinación de elementos con mas del 93 % de cuarzo , resinas ,tintes y otros secretos de la industria. Sencillez y sobriedad para tus espacios, inspírate, diseña y crea tus espacios deseados",
      },
      {
        id: "14",
        title: "BEIGE POLAR CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: " Laminas de cuarzo Hipo alergénicas de alta calidad. Quartzstone con gran fuerza estética, que hace posible decoraciones en perfecto equilibrio junto a tonos neutros o complementarios y que destaca sobremanera en escenarios de líneas más puras en color y mobiliario.",
      },
      {
        id: "15",
        title: "BLANCO CHISPAS CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "BLANCO CHISPAS CHAPA Un  lenguaje cromático único por la pureza de su blanco, nunca antes  visto en su gama tonal. Impoluta y resplandeciente, permite componer superficies de una bella pulcritud visual, en conexión con idílicos paisajes nevados. Con su presencia, esta gran familia de QUARTZSTONE alcanza una nueva dimensión estética para el campo de las aplicaciones, sin perder de vista los beneficios propios de estas piedras milenarias: dureza extrema, elevada resistencia y fácil mantenimiento.",
      },
      {
        id: "16",
        title: "BLANCO POLAR CUARZO",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Laminas de cuarzo Grupo Quartz Amplia variedad en colores y superficies. Su elegancia atemporal, su dureza sobresaliente y su resistencia a la abrasión lo convierten en un material perfecto para exteriores e interiores. Con él la autenticidad y la funcionalidad son sinónimo de una belleza innovadora.",
      },
      {
        id: "17",
        title: "CAFÉ CHISPAS CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Laminas de cuarzo Grupo Quartz , respaldo, calidad y experiencia. Estos  son cautivadores y desafiantes. El QUARTZSTONE CAFÉ CHISPAS de gran intensidad visual es sinónimo de una elegancia terrenal sublime.",
      },
      {
        id: "18",
        title: "GRIS CLARO CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Laminas de cuarzo de  1.80 x 3.20  Grupo Quartz. Con una belleza muy radical. Así llega el QUARTZSTONE Gris oscuro a las decoraciones domésticas que apuestan por las soluciones audaces y a la última tendencia.",
      },
      {
        id: "19",
        title: "GRIS POLAR CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "laminas de cuarzo de superior calidad. La magnífica personalidad del QUARTZSTONE y sus imbatibles propiedades técnicas, las convierten en las piedras naturales más cotizadas y codiciadas del momento. La mejor opción para superficies de cocinas, mesas, paredes interiores o lavados. Las diferentes variedades QUARTZSTONE ofrecen una amplia gama de tonos y patrones que agregan su belleza a los beneficios de este material famoso por su  dureza y personalidad.Catalogo - Emporeo stone",
      },
  
      {
        id: "20",
        title: "NEGRO CHISPAS CHAPA",
        price: 115.0,
        image: "https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
        image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
        image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
        category: "Quartone",
        disp:"2",
        desc: "Su impenetrable negro, imagen misma de la sobriedad y la elegancia extrema, NEGRO CHISPAS  enamora por su contundente presencia y su versatilidad estética. El negro va bien con todo, y en especial el de este producto que ofrece un color sin fisuras, totalmente puro. En ambientes claros, con blancos y crudos, el contraste de NEGRO CHISPAS será exquisito: un binomio cromático tradicional con garantía de éxito seguro; pero si además se integra en una decoración high tech, con superficies vestidas de acero, cristal y muebles de líneas rectas, el resultado estético será la quintaesencia de una fría sofisticación. Este producto no desmerece tampoco en atmósferas más cálidas, con colores y texturas suaves que contrarrestan su fuerza.",
      },
      {
        id: "45",
        title: "CALATTA",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/calacatta-2-960x1280-800x808.jpeg",
        image02:"https://maxirocas.com/assets/images/calacatta-2-960x1280-800x808.jpeg",
        image03: "https://maxirocas.com/assets/images/calacatta-2-960x1280-800x808.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "46",
        title: "CARRARA",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/carrara-5-960x1280-798x788.jpeg",
        image02:"https://maxirocas.com/assets/images/carrara-5-960x1280-798x788.jpeg",
        image03: "https://maxirocas.com/assets/images/carrara-5-960x1280-798x788.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
  
      {
        id: "47",
        title: "NEGRO CHISPAS",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/negro-chispas.webp",
        image02:"https://maxirocas.com/assets/images/negro-chispas.webp",
        image03: "https://maxirocas.com/assets/images/negro-chispas.webp",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      
      {
        id: "48",
        title: "BLANCO EXTRA",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/blanco-extra-2-1280x960-800x784.jpeg",
        image02:"https://maxirocas.com/assets/images/blanco-extra-2-1280x960-800x784.jpeg",
        image03: "https://maxirocas.com/assets/images/blanco-extra-2-1280x960-800x784.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "49",
        title: "BLANCO POPULAR",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/blanco-polar-1280x960-800x776.jpeg",
        image02:"https://maxirocas.com/assets/images/blanco-polar-1280x960-800x776.jpeg",
        image03: "https://maxirocas.com/assets/images/blanco-polar-1280x960-800x776.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "50",
        title: "BLANCO CHISPAS",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/blanco-chispas-1280x960-800x782.jpeg",
        image02:"https://maxirocas.com/assets/images/blanco-chispas-1280x960-800x782.jpeg",
        image03: "https://maxirocas.com/assets/images/blanco-chispas-1280x960-800x782.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "51",
        title: "BEIGE PLANO",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/beige-1280x720-713x709.jpeg",
        image02:"https://maxirocas.com/assets/images/beige-1280x720-713x709.jpeg",
        image03: "https://maxirocas.com/assets/images/beige-1280x720-713x709.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "52",
        title: "BEIGE CHISPAS",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/beige-chispas-1280x720-720x713.jpeg",
        image02:"https://maxirocas.com/assets/images/beige-chispas-1280x720-720x713.jpeg",
        image03: "https://maxirocas.com/assets/images/beige-chispas-1280x720-720x713.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "53",
        title: "GRIS CHISPAS",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/whatsapp-image-2021-03-10-at-9.49.19-pm-1280x720-720x718.jpeg",
        image02:"https://maxirocas.com/assets/images/whatsapp-image-2021-03-10-at-9.49.19-pm-1280x720-720x718.jpeg",
        image03: "https://maxirocas.com/assets/images/whatsapp-image-2021-03-10-at-9.49.19-pm-1280x720-720x718.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "54",
        title: "GRIS PLANO",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/gris-plano-1280x960-800x789.jpeg",
        image02:"https://maxirocas.com/assets/images/gris-plano-1280x960-800x789.jpeg",
        image03: "https://maxirocas.com/assets/images/gris-plano-1280x960-800x789.jpeg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "55",
        title: "CAFE CHISPAS",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.15-pm-300x272-300x272.jpg",
        image02:"https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.15-pm-300x272-300x272.jpg",
        image03: "https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.15-pm-300x272-300x272.jpg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "56",
        title: "AZUL CHISPAS",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.59-pm-1280x1280-800x800.jpg",
        image02:"https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.59-pm-1280x1280-800x800.jpg",
        image03: "https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.59-pm-1280x1280-800x800.jpg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "57",
        title: "AMARILLO SHIPAS",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/unnamed-512x500-512x500.jpg",
        image02:"https://maxirocas.com/assets/images/unnamed-512x500-512x500.jpg",
        image03: "https://maxirocas.com/assets/images/unnamed-512x500-512x500.jpg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "58",
        title: "ROJO SHIPAS",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/red-mirror-640x480-480x480-480x480.jpg",
        image02:"https://maxirocas.com/assets/images/red-mirror-640x480-480x480-480x480.jpg",
        image03: "https://maxirocas.com/assets/images/red-mirror-640x480-480x480-480x480.jpg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "59",
        title: "KENIA",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/kenia-black-380x355-380x355.jpg",
        image02:"https://maxirocas.com/assets/images/kenia-black-380x355-380x355.jpg",
        image03: "https://maxirocas.com/assets/images/kenia-black-380x355-380x355.jpg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
      {
        id: "60",
        title: "CAFE EXPRESO",
        price: 115.0,
        image: "https://maxirocas.com/assets/images/cafe-expreso-380x355-380x355.jpg",
        image02:"https://maxirocas.com/assets/images/cafe-expreso-380x355-380x355.jpg",
        image03: "https://maxirocas.com/assets/images/cafe-expreso-380x355-380x355.jpg",
        category: "Quartone",
        disp:"2",
        desc: "",
      },
    ]

    return (
        <div className="app__bg container mx-auto px-5 2xl:px-0 bp">
            <h1 className="text-slate-800 font-bold text-3xl md:text-4xl lg:text-6xl my-10 lg:mt-20 lg:mb-14">
              <h1 className="app__header-h1">Cocinas</h1>
            </h1>
            <section className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3 pb-20 lg:container">
                {people.map(index =>(
                    <Article urls={index.image} />
                )) }
            </section>

    
      </div>
    )
} 
export default Galery