import React from "react"
import Article from "../../components/Article/Aritcle"


const Granitos =() =>{
    const granitos =[
        {
          id: "21",
          title: "Sandalus",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Granito de Brasil en el que se mezclan tonalidades tierra que generan en este material un gran impacto a la vista gracias a su excentricidad y elegancia. Se puede instalar en fachadas, mesones para cocina, piso o como elemento decorativo en libro abierto.",
        },
        {
          id: "22",
          title: "Alpinus",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-alpinus.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-alpinus.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-alpinus.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Tiene un fondo crema, con vetas verdosas, cafés, negras y grisáceas; tiene además en su superficie algunos brillos muy marcados que lo hacen sofisticado y muy singular.",
        },
    
        {
          id: "23",
          title: "Black Mosaic",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-black-mosaic.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-black-mosaic.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-black-mosaic.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Es uno de los materiales más exclusivos y novedosos, debido a la cantidad de piedras petrificadas que hay en él; visualmente impacta. Idóneo para evocar naturaleza al máximo. Su compactación en las montañas nos regala exclusividad absoluta en esta piedra.",
        },
        {
          id: "24",
          title: "Blanco Macaubas",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-macaubas.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-macaubas.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-macaubas.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Sus vetas delgadas de color negro sobresalen en el fondo claro cremoso que encontramos en esta piedra; genera visualmente movimiento y tranquilidad.",
        },
        {
          id: "25",
          title: "Crystal Fjord",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-crystal-fjord-2.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-crystal-fjord-2.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-crystal-fjord-2.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Con componentes de cristal, es un exótico muy valorado. Cuenta con vetas poco comunes, simples y delicadas en tonalidades rosa claro, dorado y blanco.",
        },
        {
          id: "26",
          title: "Gaya",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-gaya.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-gaya.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-gaya.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "De verdes claros a verdes matizados van sus fondos combinados con vetas grises y cafés. Es uno de los colores más desafiantes de las canteras y de las gamas más altas de las mismas; ofrece a los diseñadores y arquitectos una amplia lista de posibilidades para introducir belleza natural a los más",
        },
        {
          id: "27",
          title: "Copacabana",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-copacabana.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-copacabana.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-copacabana.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Sus vetas fuertes en color blanco, café, crema y dorado hacen resaltar su fondo negro elegante y brillante con infinitas posibilidades de aplicación en interiores y exteriores.",
        },
        {
          id: "28",
          title: "Tornado",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Esta cuarcita tiene gran acogida gracias a sus tonalidades claras parecidas al Calacatta que inspiran sobriedad y elegancia. Sus vetas grises lo hace un material excepcionalmente único y apto para cualquier tipo de espacio y proyecto.",
        },
        {
          id: "29",
          title: "Galápagos",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/05/ganito-exotico-galapagos.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/05/ganito-exotico-galapagos.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/05/ganito-exotico-galapagos.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Con sus vetas grises, cafés y cremas se vuelve uno de los materiales más versátiles en cuanto a decoración y diseño. La simpleza y limpieza de sus líneas rememora un movimiento horizontal perfecto para llevar a las tendencias de interiorismo y diseño actuales. Puede crear libro abierto para componer espacios diferenciadores y sofisticados.",
        },
        {
          id: "30",
          title: "Giotto",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-giotto.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-giotto.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-giotto.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Casi como si hubieran escrito en su superficie con un pincel, así se siente este granito natural. Resaltan sus delgadas vetas negras y grises oscuras; simples, artísticas y elegantes. Una piedra con colores tendencia.",
        },
        {
          id: "31",
          title: "Maori",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maori.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maori.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maori.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Color básico para proyectos excepcionales. Su fondo negro muy brillante refleja la veta horizontal blanca que le compone. Es un granito clásico y diferenciador.",
        },
        {
          id: "32",
          title: "Maskaratus",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maskaratus.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maskaratus.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-maskaratus.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "El Maskaratus es procedente de Brasil, impacta con sus tonos y vetas marcadas que hacen distinción entre los demás granitos exóticos. Su color principal es el verde en una mezcla arriesgada entre cremas y marrones. Es una piedra natural que presenta gran variedad en su composición lo cual hace que sea imponente y única",
        },
        {
          id: "33",
          title: "Metallic",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-metallic.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-metallic.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-metallic.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "El Metallic es un granito procedente de Brasil, su particular acabado realza la belleza de sus vetas mezcladas entre negro, matices de grises y ocres en un negro profundo que lo convierte en el protagonista de cualquier espacio donde sea instalado, ya sea para mesones de cocina, enchapes, pisos y demás.",
        },
        {
          id: "34",
          title: "Meteorus",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-meteorus.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-meteorus.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-meteorus.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Meteorus es una piedra brasilera, cuya apariencia y colores neutros genera sensación de sobriedad, sobre un fondo negro mate que combinan con vetas circulares de color purpura brillante que resaltan la belleza del material.",
        },
        {
          id: "35",
          title: "Nacarado",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-nacarado.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-nacarado.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-nacarado.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Nacarado es una piedra brasilera, con vetas en gama de dorados y bellos matices en color ámbar que aportan gran luminosidad y amplitud, dando un toque de elegancia y exclusividad al espacio. Es un material con el cual se le puede dar continuidad a la veta, haciendo una instalación en libro abierto, creando así imágenes majestuosas.",
        },
        {
          id: "36",
          title: "Rocky Mountain",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-mountain.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-mountain.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-rocky-mountain.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "El Granito Rocky Mountain (Dakota) es de origen brasilero, tiene una mezcla de vetas en colores crema, grises, negro y purpura, muy dinámicas, que le dan una apariencia muy sofisticada y elegante. Ideal para mesones, barras, escaleras, enchapes y demás.",
        },
        {
          id: "37",
          title: "Roma Imperiale",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-roma-imperale.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Roma Imperiale es un granito de Brasil único y acogedor. Ofrece un fondo claro atravesado por vetas brillantes de oro, ocre y marrón. Su aspecto único es ideal para los logros originales e innovadoras de proyectos tanto para ambientes interiores y exteriores. Muy interesante es la combinación con la madera.",
        },
        {
          id: "38",
          title: "Sandalus",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-sandalus.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-sandalus.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-sandalus.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Granito de Brasil en el que se mezclan tonalidades tierra que generan en este material un gran impacto a la vista gracias a su excentricidad y elegancia. Se puede instalar en fachadas, mesones para cocina, piso o como elemento decorativo en libro abierto.",
        },
        {
          id: "39",
          title: "Santorini",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-santorini.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-santorini.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-santorini.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "El granito Santorini es de Brasil. Su alto componente de mineral de hierro le brinda una alta dureza. De color gris y vetas amarillas, naranjas y cremas. Ideal para ser el protagonista en cualquier espacio.",
        },
        {
          id: "40",
          title: "Splendor Gold",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-splendor-gold.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-splendor-gold.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-splendor-gold.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "El splendor gold es de origen brasilero, en este material se plasma una mezcla entre dorado, beige, negro y marrón con reflejos tornasol que logra un balance armonioso y hacen de este granito un material fácil de combinar y de generar contrastes.",
        },
        {
          id: "41",
          title: "Tornado",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-tornado.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Esta cuarcita tiene gran acogida gracias a sus tonalidades claras parecidas al Calacatta que inspiran sobriedad y elegancia. Sus vetas grises lo hace un material excepcionalmente único y apto para cualquier tipo de espacio y proyecto.",
        },
        {
          id: "42",
          title: "Yellow Cuarcita",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-yellow-cuarcita.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-yellow-cuarcita.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-yellow-cuarcita.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Esta cuarcita es ideal para exteriores, gracias a su alta resistencia a los cambios de temperatura. Son muy duras y de escasa porosidad. Sus vetas mezcladas en tonos marrones, ocres y cremas hacen de este un material fácil de combinar en cualquier ambiente. En la naturaleza se encuentra prácticamente en cualquier color dependiendo de los elementos químicos que haya en la roca, siendo los más habituales los grises, amarillos, blancos y rojos. A partir de ellas se puede crear una gran cantidad de proyectos, revestimientos de superficies y otros elementos, siendo muy habituales los mesones de cocinas y las placas decorativas destinadas al exterior de las viviendas",
        },
        {
          id: "43",
          title: "Venom Light",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-venom.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-venom.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-venom.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Esta cuarcita es impactante a la vista, sus colores claros y sus vetas irregulares le dan excentricidad a cualquier proyecto. Esta cuarcita es ideal para exteriores, gracias a su alta resistencia a los cambios de temperatura. Son muy duras y de escasa porosidad.",
        },
        {
          id: "44",
          title: "Xango Red",
          price: 115.0,
          image: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-xango-red.jpg",
          image02:"https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-xango-red.jpg",
          image03: "https://marmolesyservicios.com/wp-content/uploads/2020/04/ganito-exotico-xango-red.jpg",
          category: "Granitos exoticos",
          disp:"2",
          desc: "Xango red Granito natural de origen brasilero. Tiene como particularidad que su fondo es de un llamativo tono rojo intenso en combinación con sus vetas oscuras. Es un excelente material para realizar proyectos muy específicos y exclusivos.",
        },
      ]

    return (
        <div className="app__bg container mx-auto px-5 2xl:px-0 bp">
            <h1 className="text-slate-800 font-bold text-3xl md:text-4xl lg:text-6xl my-10 lg:mt-20 lg:mb-14">
            <h1 className="app__header-h1">Granitos exoticos</h1>
            </h1>
                <section className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3 pb-20 lg:container">
                        {granitos.map(index =>(
                            <div> 
                                <Article urls={index.image} />
                            </div>
                        )) }
                </section>
      </div>
    )

}

export default Granitos 