import React from "react";
import Article from "../../components/Article/Aritcle";

const Quarztone =() =>{

    const quartone =[

        {
          id: "13",
          title: "BEIGE CHISPAS CHAPA",
          price: 115.0,
          image: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
          image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
          image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-chispas-1000x1200_c.jpg",
          category: "Quartone",
          disp:"2",
          desc: "Combinación de elementos con mas del 93 % de cuarzo , resinas ,tintes y otros secretos de la industria. Sencillez y sobriedad para tus espacios, inspírate, diseña y crea tus espacios deseados",
        },
        {
          id: "14",
          title: "BEIGE POLAR CHAPA",
          price: 115.0,
          image: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
          image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
          image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Beige-polar-1000x1200_c.jpg",
          category: "Quartone",
          disp:"2",
          desc: " Laminas de cuarzo Hipo alergénicas de alta calidad. Quartzstone con gran fuerza estética, que hace posible decoraciones en perfecto equilibrio junto a tonos neutros o complementarios y que destaca sobremanera en escenarios de líneas más puras en color y mobiliario.",
        },
        {
          id: "15",
          title: "BLANCO CHISPAS CHAPA",
          price: 115.0,
          image: "https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
          image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
          image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Blanco-chispas-2-1000x1200_c.jpg",
          category: "Quartone",
          disp:"2",
          desc: "BLANCO CHISPAS CHAPA Un  lenguaje cromático único por la pureza de su blanco, nunca antes  visto en su gama tonal. Impoluta y resplandeciente, permite componer superficies de una bella pulcritud visual, en conexión con idílicos paisajes nevados. Con su presencia, esta gran familia de QUARTZSTONE alcanza una nueva dimensión estética para el campo de las aplicaciones, sin perder de vista los beneficios propios de estas piedras milenarias: dureza extrema, elevada resistencia y fácil mantenimiento.",
        },
        {
          id: "16",
          title: "BLANCO POLAR CUARZO",
          price: 115.0,
          image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
          image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
          image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-claro-1000x1200_c.jpg",
          category: "Quartone",
          disp:"2",
          desc: "Laminas de cuarzo Grupo Quartz Amplia variedad en colores y superficies. Su elegancia atemporal, su dureza sobresaliente y su resistencia a la abrasión lo convierten en un material perfecto para exteriores e interiores. Con él la autenticidad y la funcionalidad son sinónimo de una belleza innovadora.",
        },
        {
          id: "17",
          title: "CAFÉ CHISPAS CHAPA",
          price: 115.0,
          image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
          image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
          image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-cafe-chispas-1000x1200_c.jpg",
          category: "Quartone",
          disp:"2",
          desc: "Laminas de cuarzo Grupo Quartz , respaldo, calidad y experiencia. Estos  son cautivadores y desafiantes. El QUARTZSTONE CAFÉ CHISPAS de gran intensidad visual es sinónimo de una elegancia terrenal sublime.",
        },
        {
          id: "18",
          title: "GRIS CLARO CHAPA",
          price: 115.0,
          image: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
          image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
          image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Quartzstone-gris-oscuro-1000x1200_c.jpg",
          category: "Quartone",
          disp:"2",
          desc: "Laminas de cuarzo de  1.80 x 3.20  Grupo Quartz. Con una belleza muy radical. Así llega el QUARTZSTONE Gris oscuro a las decoraciones domésticas que apuestan por las soluciones audaces y a la última tendencia.",
        },
        {
          id: "19",
          title: "GRIS POLAR CHAPA",
          price: 115.0,
          image: "https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
          image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
          image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Gris-polar-1000x1200_c.jpg",
          category: "Quartone",
          disp:"2",
          desc: "laminas de cuarzo de superior calidad. La magnífica personalidad del QUARTZSTONE y sus imbatibles propiedades técnicas, las convierten en las piedras naturales más cotizadas y codiciadas del momento. La mejor opción para superficies de cocinas, mesas, paredes interiores o lavados. Las diferentes variedades QUARTZSTONE ofrecen una amplia gama de tonos y patrones que agregan su belleza a los beneficios de este material famoso por su  dureza y personalidad.Catalogo - Emporeo stone",
        },
    
        {
          id: "20",
          title: "NEGRO CHISPAS CHAPA",
          price: 115.0,
          image: "https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
          image02:"https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
          image03: "https://grupoquartz.co/wp-content/uploads/2021/05/Negro-chispas-1000x1200_c.jpg",
          category: "Quartone",
          disp:"2",
          desc: "Su impenetrable negro, imagen misma de la sobriedad y la elegancia extrema, NEGRO CHISPAS  enamora por su contundente presencia y su versatilidad estética. El negro va bien con todo, y en especial el de este producto que ofrece un color sin fisuras, totalmente puro. En ambientes claros, con blancos y crudos, el contraste de NEGRO CHISPAS será exquisito: un binomio cromático tradicional con garantía de éxito seguro; pero si además se integra en una decoración high tech, con superficies vestidas de acero, cristal y muebles de líneas rectas, el resultado estético será la quintaesencia de una fría sofisticación. Este producto no desmerece tampoco en atmósferas más cálidas, con colores y texturas suaves que contrarrestan su fuerza.",
        },
        {
          id: "45",
          title: "CALATTA",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/calacatta-2-960x1280-800x808.jpeg",
          image02:"https://maxirocas.com/assets/images/calacatta-2-960x1280-800x808.jpeg",
          image03: "https://maxirocas.com/assets/images/calacatta-2-960x1280-800x808.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "46",
          title: "CARRARA",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/carrara-5-960x1280-798x788.jpeg",
          image02:"https://maxirocas.com/assets/images/carrara-5-960x1280-798x788.jpeg",
          image03: "https://maxirocas.com/assets/images/carrara-5-960x1280-798x788.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
    
        {
          id: "47",
          title: "NEGRO CHISPAS",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/negro-chispas.webp",
          image02:"https://maxirocas.com/assets/images/negro-chispas.webp",
          image03: "https://maxirocas.com/assets/images/negro-chispas.webp",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        
        {
          id: "48",
          title: "BLANCO EXTRA",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/blanco-extra-2-1280x960-800x784.jpeg",
          image02:"https://maxirocas.com/assets/images/blanco-extra-2-1280x960-800x784.jpeg",
          image03: "https://maxirocas.com/assets/images/blanco-extra-2-1280x960-800x784.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "49",
          title: "BLANCO POPULAR",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/blanco-polar-1280x960-800x776.jpeg",
          image02:"https://maxirocas.com/assets/images/blanco-polar-1280x960-800x776.jpeg",
          image03: "https://maxirocas.com/assets/images/blanco-polar-1280x960-800x776.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "50",
          title: "BLANCO CHISPAS",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/blanco-chispas-1280x960-800x782.jpeg",
          image02:"https://maxirocas.com/assets/images/blanco-chispas-1280x960-800x782.jpeg",
          image03: "https://maxirocas.com/assets/images/blanco-chispas-1280x960-800x782.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "51",
          title: "BEIGE PLANO",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/beige-1280x720-713x709.jpeg",
          image02:"https://maxirocas.com/assets/images/beige-1280x720-713x709.jpeg",
          image03: "https://maxirocas.com/assets/images/beige-1280x720-713x709.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "52",
          title: "BEIGE CHISPAS",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/beige-chispas-1280x720-720x713.jpeg",
          image02:"https://maxirocas.com/assets/images/beige-chispas-1280x720-720x713.jpeg",
          image03: "https://maxirocas.com/assets/images/beige-chispas-1280x720-720x713.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "53",
          title: "GRIS CHISPAS",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/whatsapp-image-2021-03-10-at-9.49.19-pm-1280x720-720x718.jpeg",
          image02:"https://maxirocas.com/assets/images/whatsapp-image-2021-03-10-at-9.49.19-pm-1280x720-720x718.jpeg",
          image03: "https://maxirocas.com/assets/images/whatsapp-image-2021-03-10-at-9.49.19-pm-1280x720-720x718.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "54",
          title: "GRIS PLANO",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/gris-plano-1280x960-800x789.jpeg",
          image02:"https://maxirocas.com/assets/images/gris-plano-1280x960-800x789.jpeg",
          image03: "https://maxirocas.com/assets/images/gris-plano-1280x960-800x789.jpeg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "55",
          title: "CAFE CHISPAS",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.15-pm-300x272-300x272.jpg",
          image02:"https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.15-pm-300x272-300x272.jpg",
          image03: "https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.15-pm-300x272-300x272.jpg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "56",
          title: "AZUL CHISPAS",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.59-pm-1280x1280-800x800.jpg",
          image02:"https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.59-pm-1280x1280-800x800.jpg",
          image03: "https://maxirocas.com/assets/images/whatsapp-image-2021-02-22-at-10.45.59-pm-1280x1280-800x800.jpg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "57",
          title: "AMARILLO SHIPAS",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/unnamed-512x500-512x500.jpg",
          image02:"https://maxirocas.com/assets/images/unnamed-512x500-512x500.jpg",
          image03: "https://maxirocas.com/assets/images/unnamed-512x500-512x500.jpg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "58",
          title: "ROJO SHIPAS",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/red-mirror-640x480-480x480-480x480.jpg",
          image02:"https://maxirocas.com/assets/images/red-mirror-640x480-480x480-480x480.jpg",
          image03: "https://maxirocas.com/assets/images/red-mirror-640x480-480x480-480x480.jpg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "59",
          title: "KENIA",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/kenia-black-380x355-380x355.jpg",
          image02:"https://maxirocas.com/assets/images/kenia-black-380x355-380x355.jpg",
          image03: "https://maxirocas.com/assets/images/kenia-black-380x355-380x355.jpg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
        {
          id: "60",
          title: "CAFE EXPRESO",
          price: 115.0,
          image: "https://maxirocas.com/assets/images/cafe-expreso-380x355-380x355.jpg",
          image02:"https://maxirocas.com/assets/images/cafe-expreso-380x355-380x355.jpg",
          image03: "https://maxirocas.com/assets/images/cafe-expreso-380x355-380x355.jpg",
          category: "Quartone",
          disp:"2",
          desc: "",
        },
      ]

    return (
        <div className="app__bg container mx-auto px-5 2xl:px-0 bp">
            <h1 className="text-slate-800 font-bold text-3xl md:text-4xl lg:text-6xl my-10 lg:mt-20 lg:mb-14">
            <h1 className="app__header-h1">Quarztones</h1>
            </h1>
                <section className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3 pb-20 lg:container">
                    {quartone.map(index =>(
                        <div> 
                            <Article urls={index.image} />
                        </div>
                    )) }
                </section>
      </div>
    )

}
export default Quarztone